### ISSUE TITLE
Please remove secret from github! ;)

### ISSUE THREAD

**Issue by steinbrueckri** [progettoIspw2019/FixMyCity#15]
https://github.com/progettoIspw2019/FixMyCity/blob/04638c2ced009da741ea14f0d10156bf8db19b90/.travis.yml#L16

```
Dsonar.organization=progettoispw2019
Dsonar.login=791af94481812a17969d521fe631ec3db52decd4
Dsonar.projectKey=progettoIspw2019_FixMyCity 
```

**Comment by steinbrueckri** [comment]
@gleichda @kunzese @oswalya

**Comment by adrianrob1** [comment]
Yeah, that might be an issue
Never thought someone would take a look at our project honestly 😄 
It's our first application built in java, so we might do a lot of stuff the wrong way

**Comment by steinbrueckri** [comment]
https://docs.travis-ci.com/user/encryption-keys/ ;)

**Comment by progettoIspw2019** [comment]
Thanks! Will fix this asap
Do you know how the fact that this login token is now public might affect us? I mean, should we change that token and in that case is there a way to change it?

**Comment by steinbrueckri** [comment]
Yes please go and change the token ...
https://sonarcloud.io/documentation/user-guide/user-token/

**Comment by adrianrob1** [comment]
Thanks a lot 😄 
I revoked that token, created an environment variable with the new Sonar token in Travis-CI, and made it so it's only accessible to our branch
