### ISSUE TITLE
Make use of Liquibase

### ISSUE THREAD

**Issue by steinbrueckri** [progettoIspw2019/FixMyCity#17]
Hi Guys,
I have seen you add your DB Schema via SQL file to the Repository. Just an recommendation from my side, make use of tool like Liquibase to track your DB Schema Changes.

https://www.liquibase.org/index.html

https://github.com/progettoIspw2019/FixMyCity/blob/b51cc582ef7ee92d413138083f6514f2cc7487ba/db.sql#L1

**Comment by adrianrob1** [comment]
Thanks again!
I took a look and it seemed really interesting. It seems to me that the main feature is automating the schema loading to the DB, is there some other functionality we could make use of?
